version: '3'

services:

  app-prod:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        CI_BUILD_ID: ${CI_BUILD_ID}
        CI_BUILD_REF: ${CI_BUILD_REF}
        CI_BUILD_TIME: ${CI_BUILD_TIME}
        CI_REGISTRY_IMAGE: ${CI_REGISTRY_IMAGE}
    image: ${APP_PROD_IMAGE:-acme101/lemp-starter:develop}
    environment:
      VIRTUAL_HOST: ${APP_PROD_VIRTUAL_HOST:-lemp.acme.dev, ~^lemp\..*\.xip\.io}
      HTTPS_METHOD: noredirect # support both http and https
    env_file:
      - .env-common
      - .env-prod
    depends_on:
      - db-dev
    links:
      - db-dev:db
    network_mode: bridge
