version: '3'

services:

  app-dev:
    image: ${APP_DEV_IMAGE:-richarvey/nginx-php-fpm:1.2.3}
    working_dir: /opt/app
    command: sh run-dev.sh
    environment:
      PORT: 8080
      VIRTUAL_HOST: ${APP_DEV_VIRTUAL_HOST:-dev.lemp.acme.dev, ~^dev\.lemp\..*\.xip\.io}
      VIRTUAL_PORT: 8080
      HTTPS_METHOD: noredirect # support both http and https    
    env_file:
      - .env-common
      - .env-dev
    ports:
      - "8080"
    depends_on:
      - db-dev
    links:
      - db-dev:db
    volumes:
      - ./src:/var/www/html
      - ./run-dev.sh:/opt/app/run-dev.sh
      - ./nginx:/opt/app/nginx
    restart: unless-stopped
    network_mode: bridge

  phpmyadmin-dev:
    image: ${PHP_MY_ADMIN_DEV_IMAGE:-phpmyadmin/phpmyadmin:4.7.3-1}
    environment:
      VIRTUAL_HOST: ${PHP_MY_ADMIN_DEV_VIRTUAL_HOST:-phpmyadmin-dev.lemp.acme.dev, ~^phpmyadmin-dev\.lemp.\..*\.xip\.io}
      HTTPS_METHOD: noredirect # support both http and https
    depends_on:
      - db-dev
    links:
      - db-dev:db
    restart: unless-stopped
    network_mode: bridge

  db-dev:
    image: ${DB_DEV_IMAGE:-mariadb:10.2.7}
    environment:
      MYSQL_ROOT_PASSWORD: teracy # login with root:teracy as root user
      MYSQL_DATABASE: app
      MYSQL_USER: teracy
      MYSQL_PASSWORD: teracy # login with teracy:teracy as user of the "app" database
    volumes:
      - db-dev:/var/lib/mysql
    restart: unless-stopped
    network_mode: bridge

volumes:
  db-dev:
    driver: local
