version: '3'

services:

  app-review:
    image: ${APP_REVIEW_IMAGE}
    environment:
      VIRTUAL_HOST: ${APP_REVIEW_VIRTUAL_HOST:-review.lemp.acme.dev, ~^review\.lemp\..*\.xip\.io}
      HTTPS_METHOD: noredirect # support both http and https
    env_file:
      - .env-common
      - .env-review
    depends_on:
      - db-review
    links:
      - db-review:db
    network_mode: bridge

  phpmyadmin-review:
    image: ${PHP_MY_ADMIN_REVIEW_IMAGE:-phpmyadmin/phpmyadmin:4.7.3-1}
    environment:
      VIRTUAL_HOST: ${PHP_MY_ADMIN_REVIEW_VIRTUAL_HOST:-phpmyadmin-review.lemp.acme.dev, ~^phpmyadmin-review.lemp.\..*\.xip\.io}
      HTTPS_METHOD: noredirect # support both http and https
    depends_on:
      - db-review
    links:
      - db-review:db
    restart: unless-stopped
    network_mode: bridge

  db-review:
    image: ${DB_REVIEW_IMAGE:-mariadb:10.2.7}
    environment:
      MYSQL_ROOT_PASSWORD: teracy # login with root:teracy as root user
      MYSQL_DATABASE: app
      MYSQL_USER: teracy
      MYSQL_PASSWORD: teracy # login with teracy:teracy as user of the "app" database
    volumes:
      - db-review:/var/lib/mysql
    restart: unless-stopped
    network_mode: bridge

volumes:
  db-review:
    driver: local
